url			: "https://aidil.me"
baseurl		: ""

title			: Aidil Putra
author			: Aidil Putra
copyright		: aidil

email			: putra@aidil.me
twitter_username	: aidil_chaniagoo
github_username	: aidilchaniagoo
facebook_id		: chaniagoo1
tracking_id		: UA-112182634-1


site_heading		: Aidil <span class="faded">'s blog</span>
description		: Personal Blog, membahas tutorial Linux, Firewall dan Program.
about_stub		: Personal Blog, membahas tutorial Linux, Firewall dan Program.

profile_picture		: images/temp.jpeg
paginate		: 5
paginate_path		: "/page/:num"

og_image		: "images/accent.png"
twitter_image		: "https://ankitsultana.com/images/accent.png?1234" 

comments		: true
permalink		: /:title.html
about_footer		: true


markdown		: kramdown
plugins			: ['jekyll-paginate']
sass:
    style: compressed
    sass_dir: _sass

defaults		:
    -
        scope:
            path:   ""
            type:   "pages"
        values:
            layout: "page"
    -
        scope:
            path:   ""
            type:   "posts"
        values:
            layout: "post"

compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all

exclude			: ['vendor', 'LICENSE', 'README.md', 'CNAME']
